### ISSUE TITLE
Setup a test suite

### ISSUE THREAD

**Issue by abhiaiyer91** [abhiaiyer91/GraphQL-Chat#3]
Test Suite would be nice for unit testing resolvers

**Comment by Darkbladecr** [comment]
Shall we use [Mocha](https://mochajs.org/)? Or do you have any other suggestions?

**Comment by abhiaiyer91** [comment]
Lets use Mocha or Ava?

**Comment by Darkbladecr** [comment]
Ava looks cool! Let's give it a go!

**Comment by Darkbladecr** [comment]
I have added Ava, along with the config, but it seems to have issues importing files?
I don't have any experience with AVA do you mind having a quick look?
Also how do you think it is best to run the test? I think it is best to run a standalone vanilla JS graphql-client, however do we require the server to be running, or import and run directly from the test files?

**Comment by abhiaiyer91** [comment]
Definitely!

Well for our server API, we just need test out the backend. The Front End projects should be the ones testing out queries and mutations and even then it'll be a mock level.

Will jump on this today!

**Comment by Darkbladecr** [comment]
Fine so you think we should test the standalone resolvers?
How will we test the pubsub system?
